export const merchantDataStructure = {
  user_id: '',
  company_name: '',
  logo_url: '',
  slogan: '',
  registration_number: '',
  established_year: null,
  headquarters_location: '',
  branch_locations: [],
  business_type: '',
  phone_number: '',
  email_address: '',
  website: '',
  social_media_links: {
    facebook: '',
    twitter: '',
    instagram: '',
    youtube: '',
    line: '',
  },
  contact_person_name: '',
  position_designation: '',
  emergency_contact_number: '',
  tourism_license_number: '',
  tin: '',
  business_permits: [],
  membership_certificates: [],
  documents: [],
  addressDetails: {
    country: '',
    province: '',
    city: '',
    zip_code: '',
    address_details: '',
  },
}
